import FormField from '~/components/FormField';

const Home = () => {
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>
          Browse through a collection of imaginative and visually stunning images generated by
          DALL-E AI
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        <>
          <h2 className='font-medium text-[#666e75] text-xl mb-3'>
            Showing Resuls for <span className='text-[#222328]'>text</span>:
          </h2>

          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'></div>
        </>
      </div>
    </section>
  );
};

export default Home;
